<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <?php if ($_product->getTypeId() != "budget_product_type") :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
    <?php elseif ($_product->getTypeId() == "budget_product_type"):?>
    
    <div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
        <button data-mage-init='{"callforprice": "{}"}' type="button" class="btn btn-primary btn-lg" id="popupButton" data-toggle="modal"
        data-target="#myModal"><?php echo __('Call for price')?></button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

    <?php endif; ?>
<?php endif; ?>

<div class="modal fade" id="myModal" role="dialog" style="display:none;">
    <div class="modal-dialog">

        <form action="<?php echo $block->getBaseUrl() . 'ProductBudget/index/post'; ?>" method="post">
            <div class="form-group">
                <label for="name"><?php echo __('Name');?>:</label>
                <input type="text" class="form-control" id="name" placeholder="<?php echo __('Enter name')?>" name="name">
            </div>
            <div class="form-group">
                <label for="email"><?php echo __('E-mail');?></label>
                <input type="email" class="form-control" id="email" placeholder="<?php echo __('Enter email')?>" name="email"> 
            </div>
            <div class="form-group">
                <label for="phone"><?php echo __('Phone number');?></label>
                <input type="text" class="form-control" id="email" placeholder="<?php echo __('Enter phone number')?>" name="phone">       
            </div>
    
            <button type="submit" class="btn btn-default"><?php echo __('Submit')?></button>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
